marchand_achat:
    resource: "@MarchandBundle/Resources/config/routing/achat.yml"
    prefix:   /achat

marchand_fruit:
    resource: "@MarchandBundle/Resources/config/routing/fruit.yml"
    prefix:   /fruit

marchand_homepage:
    path:     /
    defaults: { _controller: MarchandBundle:Default:index }

marchand_users_delete:
    path:     /marchand/users/{id}/delete
    defaults: { _controller: "MarchandBundle:Achat:userDelete" }

marchand_user_new:
    path:     /marchand/users/new
    defaults: { _controller: "MarchandBundle:Achat:newUser" }
