MarchandBundle\Entity\Achat:
    type: entity
    table: null
    repositoryClass: MarchandBundle\Repository\AchatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantite:
            type: integer
        total:
            type: string
            length: 255


    manyToOne:
        fruit:
            targetEntity: MarchandBundle\Entity\Fruit
            inversedBy: achats
        client:
            targetEntity: MarchandBundle\Entity\User
            inversedBy: id
            joinColumn:
                onDelete: CASCADE


    lifecycleCallbacks: {  }
