achat_index:
    path:     /
    defaults: { _controller: "MarchandBundle:Achat:index" }
    methods:  GET

achat_show:
    path:     /{id}/show
    defaults: { _controller: "MarchandBundle:Achat:show" }
    methods:  GET

achat_new:
    path:     /new
    defaults: { _controller: "MarchandBundle:Achat:new" }
    methods:  [GET, POST]

achat_edit:
    path:     /marchand/{id}/edit
    defaults: { _controller: "MarchandBundle:Achat:edit" }
    methods:  [GET, POST]

achat_delete:
    path:     /marchand/{id}/delete
    defaults: { _controller: "MarchandBundle:Achat:delete" }
    methods:  DELETE

achat_index_marchand:
    path:     /marchand/
    defaults: { _controller: "MarchandBundle:Achat:indexMarchand" }
    methods:  GET

achat_new_marchand:
    path:     /marchand/new
    defaults: { _controller: "MarchandBundle:Achat:newMarchand" }
    methods:  [GET, POST]

achat_show_marchand:
    path:     /marchand/{id}/show
    defaults: { _controller: "MarchandBundle:Achat:showMarchand" }
    methods:  GET

